
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Apr 03 01:07:00 CST 2016
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PT = 58;
  public static final int CONS = 48;
  public static final int QUERY = 51;
  public static final int SUCURSAL = 45;
  public static final int DE = 50;
  public static final int TIPO = 35;
  public static final int POR = 4;
  public static final int T = 27;
  public static final int R = 23;
  public static final int MD = 57;
  public static final int P = 26;
  public static final int XOR = 9;
  public static final int MYR = 8;
  public static final int CIERRAC = 61;
  public static final int FECHA = 11;
  public static final int CU = 28;
  public static final int TAM = 44;
  public static final int D = 22;
  public static final int IU = 24;
  public static final int NOT = 55;
  public static final int AND = 54;
  public static final int IGUAL = 21;
  public static final int EXTRAER = 49;
  public static final int OR = 53;
  public static final int GET = 56;
  public static final int NOM = 29;
  public static final int RQ = 59;
  public static final int DIV = 5;
  public static final int TIPO2 = 40;
  public static final int DIR = 33;
  public static final int FECHAC = 20;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMILLA = 10;
  public static final int COMA = 6;
  public static final int MARCA = 42;
  public static final int MENOS = 3;
  public static final int ABREC = 60;
  public static final int BAJO = 15;
  public static final int IDE = 25;
  public static final int CANT = 41;
  public static final int APE = 30;
  public static final int COLOR = 43;
  public static final int IMG = 38;
  public static final int EM = 32;
  public static final int PUNTOS = 14;
  public static final int id = 63;
  public static final int PROP = 37;
  public static final int PUNTO = 13;
  public static final int COD = 36;
  public static final int MNR = 7;
  public static final int TIENDA = 34;
  public static final int PUNTOC = 12;
  public static final int PROD = 46;
  public static final int PARC = 17;
  public static final int DONDE = 52;
  public static final int PARA = 16;
  public static final int CADS = 64;
  public static final int num = 62;
  public static final int LLAVEC = 19;
  public static final int MATE = 47;
  public static final int LLAVEA = 18;
  public static final int TEL = 31;
  public static final int PROP2 = 39;
  public static final int MAS = 2;
}

