
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 26 19:27:39 CST 2016
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PT = 59;
  public static final int CONS = 49;
  public static final int QUERY = 52;
  public static final int SUCURSAL = 46;
  public static final int DE = 51;
  public static final int TIPO = 36;
  public static final int POR = 4;
  public static final int T = 28;
  public static final int R = 24;
  public static final int MD = 58;
  public static final int P = 27;
  public static final int XOR = 9;
  public static final int MYR = 8;
  public static final int CIERRAC = 62;
  public static final int FECHA = 12;
  public static final int CU = 29;
  public static final int TAM = 45;
  public static final int D = 23;
  public static final int IU = 25;
  public static final int NOT = 56;
  public static final int AND = 55;
  public static final int IGUAL = 22;
  public static final int EXTRAER = 50;
  public static final int OR = 54;
  public static final int GET = 57;
  public static final int NOM = 30;
  public static final int RQ = 60;
  public static final int DIV = 5;
  public static final int TIPO2 = 41;
  public static final int DIR = 34;
  public static final int FECHAC = 21;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMILLA = 11;
  public static final int COMA = 6;
  public static final int MARCA = 43;
  public static final int MENOS = 3;
  public static final int ABREC = 61;
  public static final int BAJO = 16;
  public static final int IDE = 26;
  public static final int CANT = 42;
  public static final int APE = 31;
  public static final int COLOR = 44;
  public static final int IMG = 39;
  public static final int EM = 33;
  public static final int PUNTOS = 15;
  public static final int id = 64;
  public static final int PROP = 38;
  public static final int PUNTO = 14;
  public static final int COD = 37;
  public static final int MNR = 7;
  public static final int TIENDA = 35;
  public static final int PUNTOC = 13;
  public static final int PROD = 47;
  public static final int PARC = 18;
  public static final int DONDE = 53;
  public static final int PARA = 17;
  public static final int CADS = 10;
  public static final int num = 63;
  public static final int LLAVEC = 20;
  public static final int MATE = 48;
  public static final int LLAVEA = 19;
  public static final int TEL = 32;
  public static final int PROP2 = 40;
  public static final int MAS = 2;
}

